package com.handicraftgallery.handicraftgallery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BillingInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String fullName;
	private java.lang.String postalCode;
	private java.lang.String street;
	private java.lang.String city;

	public BillingInformation() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(java.lang.String postalCode) {
		this.postalCode = postalCode;
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public BillingInformation(java.lang.String fullName,
			java.lang.String postalCode, java.lang.String street,
			java.lang.String city) {
		this.fullName = fullName;
		this.postalCode = postalCode;
		this.street = street;
		this.city = city;
	}

}