package com.handicraftgallery.handicraftgallery;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class OrderCreateDBResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String status;
	private java.lang.String orderId;
	private java.lang.String date;
	private java.lang.String message;

	public OrderCreateDBResponse() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.String orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public OrderCreateDBResponse(java.lang.String status,
			java.lang.String orderId, java.lang.String date,
			java.lang.String message) {
		this.status = status;
		this.orderId = orderId;
		this.date = date;
		this.message = message;
	}

}