package com.handicraftgallery.handicraftgallery;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class User implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String lastName;
	private java.lang.String email;
	private String phoneNumber;

	private java.lang.String firstName;

	private java.lang.String password;

	public User() {
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public User(java.lang.String lastName, java.lang.String email,
			java.lang.String phoneNumber, java.lang.String firstName,
			java.lang.String password) {
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.firstName = firstName;
		this.password = password;
	}

}